name: Build MobileGlues for Android


on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v4

    # 可选：安装 Android NDK
    # - uses: android-actions/setup-android@v3
    #   with:
    #     ndk: true

    - name: Configure CMake
      run: |
        cd src/main/cpp
        mkdir -p build
        git clone --depth 1 https://github.com/g-truc/glm.git include/glm
        git clone --depth 1 https://github.com/stbrumme/xxhash.git 3rdparty/xxhash
        cmake -B build \
        -DANDROID_ABI=arm64-v8a \
        -DANDROID_PLATFORM=android-29 \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
        -DANDROID_TOOLCHAIN=clang

    - name: Build
      run: cmake --build src/main/cpp/build --config Release --target mobileglues

    - name: Install llvm
      run: sudo apt-get update && sudo apt-get install -y llvm

    - name: Strip
      run: |
        cd src/main/cpp/build/
        llvm-strip libmobileglues.so

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: MobileGlues
        path: src/main/cpp/build/libmobileglues.so
