name: Build MobileGlues for Android

on:
  workflow_dispatch:
  
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:      
      fail-fast: false

    steps:
    - uses: actions/checkout@main

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
            cd src/main/cpp
            mkdir -p build
            git clone --depth 1 https://github.com/g-truc/glm.git src/main/cpp/include/glm
            git clone --depth 1 https://github.com/stbrumme/xxhash.git src/main/cpp/3rdparty/xxhash
            cmake -B build \
            -DANDROID_ABI="arm64-v8a" \
            -DANDROID_PLATFORM="android-29" \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_TOOLCHAIN=clang

    - name: Build
      run: cmake --build build --config RelWithDebInfo --target mobileglues
      

    - name: Strip
      run: |
        cd src/main/cpp/build/
        strip --strip-all libmobileglues.so



    - name: Upload
      uses: actions/upload-artifact@main
      with:
        name: MobileGlues
        path: build/libmobileglues.so
