name: Build MobileGlues for Android

on:
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo
  ANDROID_ABI: arm64-v8a
  ANDROID_PLATFORM: android-29
  NDK_VERSION: "25.1.8937393"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Android NDK
      uses: android-actions/setup-android-ndk@v1
      with:
        ndk-version: ${{ env.NDK_VERSION }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build ccache

    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: |
          ~/.ccache
          src/main/cpp/3rdparty
        key: ${{ runner.os }}-ccache-${{ hashFiles('CMakeLists.txt') }}

    - name: Fetch external libraries
      run: |
        mkdir -p src/main/cpp/3rdparty
        git clone --depth 1 --branch stable https://github.com/g-truc/glm.git src/main/cpp/include/glm || true
        git clone --depth 1 https://github.com/stbrumme/xxhash.git src/main/cpp/3rdparty/xxhash || true
    - name: Configure CMake
      run: |
        cd src/main/cpp
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -DANDROID_ABI=${{ env.ANDROID_ABI }} \
          -DANDROID_PLATFORM=${{ env.ANDROID_PLATFORM }} \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

    - name: Build with Ninja
      run: |
        cd src/main/cpp/build
        ninja -j $(nproc) mobileglues

    - name: Strip binary
      run: |
        $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip \
          --strip-all src/main/cpp/build/libmobileglues.so

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MobileGlues
        path: src/main/cpp/build/libmobileglues.so
